import Head from "next/head";
import Image from "next/future/image";
import Link from "next/link";
import Layout from "src/components/Layout";
import Script from "next/script";

import haxeFlixelImg from "$images/haxeflixel.svg";
import windowsLogo from "$images/targets/windows-logo.svg";
import linuxLogo from "$images/targets/linux-logo.svg";
import appleLogo from "$images/targets/apple-logo.svg";
import androidLogo from "$images/targets/android-logo.svg";
import iosLogo from "$images/targets/ios-logo.png";
import flashLogo from "$images/targets/flash-logo.svg";
import html5Logo from "$images/targets/html5-logo.svg";

import { demoData } from "$data/demos";

import type { NextPage } from "next";

const Home: NextPage = () => (
  <Layout>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="container">
      <div className="home-header home-section">
        <Link href="documentation/about">
          <a className="home-big-logo" title="About HaxeFlixel">
            <Image src={haxeFlixelImg} width="200" height="200" alt="HaxeFlixel Logo" />
          </a>
        </Link>
        <h1>HaxeFlixel</h1>

        <p className="lead-line">
          Create cross-platform games easier and free. <br />
          All with one codebase.
        </p>

        <p>
          <a className="button-style home-button" href="/documentation/getting-started">
            Getting Started
          </a>
          <a className="button-style home-button" href="https://github.com/HaxeFlixel">
            GitHub
          </a>
        </p>
        <hr className="backer-hr" />

        <div className="home-social">
          <iframe
            width="160px"
            scrolling="0"
            height="30px"
            frameBorder="0"
            src="https://ghbtns.com/github-btn.html?user=HaxeFlixel&amp;repo=flixel&amp;type=watch&amp;count=true&amp;size=large"
          ></iframe>

          <iframe
            width="160px"
            scrolling="0"
            height="30px"
            frameBorder="0"
            src="https://ghbtns.com/github-btn.html?user=HaxeFlixel&amp;repo=flixel&amp;type=fork&amp;count=true&amp;size=large"
          ></iframe>

          <br />

          <a
            href="https://twitter.com/haxeflixel"
            className="twitter-follow-button"
            data-show-count="true"
            data-lang="en"
            data-size="large"
          >
            Follow @haxeflixel
          </a>

          <Script id="twitter-follow-badge" src="https://platform.twitter.com/widgets.js" />

          <br />
          <a href="https://discordapp.com/invite/rqEBAgF">
            <Image
              src="https://img.shields.io/discord/162395145352904705.svg?logo=discord"
              alt="Discord"
              width="119"
              height="20"
            />
          </a>
          <a href="https://www.patreon.com/haxeflixel">
            <Image src="https://img.shields.io/badge/donate-patreon-blue.svg" alt="Patreon" width="100" height="20" />
          </a>
        </div>

        <hr className="backer-hr" />

        <section className="home-section">
          <p className="lead-line-large">
            Cross-compile your games <a href="documentation/about">natively</a> to:
          </p>

          <div className="platform-logos-home">
            <Image width={80} height={80} src="/images/targets/windows-logo.svg" alt="Windows" title="Windows" />
            <Image width={80} height={85} src={linuxLogo} alt="Linux" title="Linux" />
            <Image width={80} height={85} src={appleLogo} alt="Mac" title="Mac" />
            <Image width={80} height={85} src={androidLogo} alt="Android" title="Android" />
            <Image width={100} height={64} src={iosLogo} alt="iOS" title="iOS" />
            <Image width={80} height={80} src={flashLogo} alt="Flash" title="Flash" />
            <Image width={85} height={85} src={html5Logo} alt="HTML5" title="HTML5" />
          </div>
        </section>
        <hr />
        <section className="demos-home home-section">
          <p className="lead-line-large">
            Browse and learn from our <a href="/demos">{demoData.length} demos</a>:
          </p>
          <div className="demo-img-section">
            {demoData.map((demo, idx) => (
              <Image
                key={idx}
                width={160}
                height={160}
                src={`/images/demos/${demo.title}.png`}
                alt={demo.title}
                title={demo.title}
              />
            ))}
          </div>
        </section>
        <hr />
        <section className="home-section-powered">
          <p className="lead-line-large">Powered by open source cross-platform tech:</p>
          <br />

          <Image src="/images/haxe.svg" alt="Haxe Logo" height="120" width="120" />
          <span className="plus-sign">+</span>
          <Image src="/images/openfl.svg" alt="OpenFL Logo" height="120" width="120" />
          <span className="plus-sign">+</span>
          <Image src="/images/flixel.svg" alt="Haxe Logo" height="120" width="120" />
          <span className="plus-sign">=</span>
          <Image src="/images/haxeflixel.svg" alt="Haxe Logo" height="120" width="120" />
        </section>
      </div>
    </main>
  </Layout>
);

export default Home;
