import Head from "next/head";
import Image from "next/future/image";
import Link from "next/link";
import Layout from "src/components/Layout";

import haxeFlixelImg from "$images/haxeflixel.svg";

import type { NextPage } from "next";

const Home: NextPage = () => (
  <Layout>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="container">
      <div className="home-header home-section">
        <Link href="documentation/about">
          <a className="home-big-logo" title="About HaxeFlixel">
            <Image src={haxeFlixelImg} width="200" height="200" alt="HaxeFlixel Logo" />
          </a>
        </Link>
        <h1>HaxeFlixel</h1>

        <p className="lead-line">
          Create cross-platform games easier and free. <br />
          All with one codebase.
        </p>

        <p>
          <a className="button-style home-button" href="/documentation/getting-started">
            Getting Started
          </a>
          <a className="button-style home-button" href="https://github.com/HaxeFlixel">
            GitHub
          </a>
        </p>
        <hr className="backer-hr" />

        <div className="home-social">
          <iframe
            width="160px"
            scrolling="0"
            height="30px"
            frameBorder="0"
            src="https://ghbtns.com/github-btn.html?user=HaxeFlixel&amp;repo=flixel&amp;type=watch&amp;count=true&amp;size=large"
          ></iframe>

          <iframe
            width="160px"
            scrolling="0"
            height="30px"
            frameBorder="0"
            src="https://ghbtns.com/github-btn.html?user=HaxeFlixel&amp;repo=flixel&amp;type=fork&amp;count=true&amp;size=large"
          ></iframe>

          <br />

          <a
            href="https://twitter.com/haxeflixel"
            className="twitter-follow-button"
            data-show-count="true"
            data-lang="en"
            data-size="large"
          >
            Follow @haxeflixel
          </a>

          {/* <Script
        id="twitter-js"
        src="https://js.stripe.com/v3/"
        onLoad={() => {
          !function (d, s, id)
            {
                var js, fjs = d.getElementsByTagName (s)[0];
                if (!d.getElementById (id))
                {
                    js = d.createElement (s);
                    js.id = id;
                    js.src = "//platform.twitter.com/widgets.js";
                    fjs.parentNode.insertBefore (js, fjs);
                }
            } (document, "script", "twitter-wjs");
        }}
      /> */}

          <br />
          <a href="https://discordapp.com/invite/rqEBAgF">
            <Image
              src="https://img.shields.io/discord/162395145352904705.svg?logo=discord"
              alt="Discord"
              width="119"
              height="20"
            />
          </a>
          <a href="https://www.patreon.com/haxeflixel">
            <Image src="https://img.shields.io/badge/donate-patreon-blue.svg" alt="Patreon" width="100" height="20" />
          </a>
        </div>

        <hr className="backer-hr" />

        <div className="home-section">
          <p className="lead-line-large">
            Cross-compile your games <a href="documentation/about">natively</a> to:
          </p>

          <div className="platform-logos-home">
            <Image width={80} height={80} src="images/targets/windows-logo.svg" alt="Windows" title="Windows" />
            <Image width={80} height={85} src="images/targets/linux-logo.svg" alt="Linux" title="Linux" />
            <Image width={80} height={85} src="images/targets/apple-logo.svg" alt="Mac" title="Mac" />
            <Image width={80} height={85} src="images/targets/android-logo.svg" alt="Android" title="Android" />
            <Image width={100} height={85} src="images/targets/ios-logo.png" alt="iOS" title="iOS" />
            <Image width={80} height={80} src="images/targets/flash-logo.svg" alt="Flash" title="Flash" />
            <Image width={85} height={85} src="images/targets/html5-logo.svg" alt="HTML5" title="HTML5" />
          </div>
        </div>
      </div>
    </main>
  </Layout>
);

export default Home;
